### ISSUE TITLE
Is `fs` unique across tests?

### ISSUE THREAD

**Issue by jamesbraza** [pytest-dev/pyfakefs#872] opened 2023-08-25 00:43 UTC
I have something like the below code:

```python
import pathlib
import random
import time

import pytest
from pyfakefs.fake_filesystem import FakeFilesystem

FOLDER = (pathlib.Path(__file__).parent / "foo").resolve()
FOLDER.mkdir(exist_ok=True)
FILE = FOLDER / "file.csv"


def test_one(fs: FakeFilesystem) -> None:
    fs.create_file(FILE)
    time.sleep(random.random())
    assert FILE.exists()


@pytest.mark.usefixtures("fs")
def test_two() -> None:
    FILE.unlink(missing_ok=True)
    time.sleep(random.random() / 100)


def test_three(fs: FakeFilesystem) -> None:
    fs.create_file(FILE)
    FILE.unlink()
```

When running these tests via many processes in parallel using `tox run-parallel`, sometimes the test fails, which indicates to me the `fs` is not unique across test cases or test processes.

Is this the case?  I thought `fs` should be unique, but it seems like it isn't

**Comment by jamesbraza** [comment] 2023-08-25 00:44
This should be labelled as a "question" I think, sorry for clicking wrong button at first

**Comment by jamesbraza** [comment] 2023-08-25 00:55
Update: I think my issue is `create_file` doesn't actually patch in the file, you have to use the return of `create_file`.

So I needed to do something like this:

```python
def test_three(fs: FakeFilesystem) -> None:
    made_file = fs.create_file(FILE)
    pathlib.Path(made_file.path).unlink()
```

Feel free to close this as resolved, or leave open as an opportunity for better docs in `create_file`.

Also, one other suggestion is to make `FakeFile` objects subclasses of `pathlib.Path`.

**Comment by mrbean-bremen** [comment] 2023-08-25 05:22
> or leave open as an opportunity for better docs in create_file

I'll probaly add a link to the [API documentation](https://pytest-pyfakefs.readthedocs.io/en/latest/modules.html#pyfakefs.fake_filesystem.FakeFilesystem.create_file) in the [usage section](https://pytest-pyfakefs.readthedocs.io/en/latest/usage.html#file-creation-helpers), and adapt the summary of the API documentation make it more clear what it does.

> Also, one other suggestion is to make FakeFile objects subclasses of pathlib.Path.

As `FakeFile` is a mocked file (not a mocked `pathlib.Path` - that would be `FakePath`) and should be usable everywhere where a file can be used. As not every function handles `pathlib.Path` arguments, this is not feasible.

As an aside, your test setup is a bit unusal, as you fix real file system changes (creating that "foo" folder) with the fake filesystem - I'm not sure if this is intended. Ususally with `pyfakefs`, you don't want to change the real fs.

**Comment by jamesbraza** [comment] 2023-08-25 17:11
Thanks for the responses!  Helped fill in some missing blanks.

> as you mix real file system changes (creating that "foo" folder) with the fake filesystem - I'm not sure if this is intended

I am wondering, will `create_file` interact with the real filesystem if I use a `pathlib.Path` from the real file system?  I figured that the entire `fs: FakeFilesystem` is fake, so using a `pathlib.Path` from the real file system will not actually interact with the real filesystem when using `create_file`.

Otherwise if I wanted real filesystem interaction, I would have used `add_real_file` instead of `create_file`.

Can you confirm that `create_file` won't touch the actual file system, even if the `pathlib.Path` comes from the real file system?

---

Also, you're right per `create_file` returning a `FakeFile` not a `FakePath`, I realize that now 😅.

What do you think of `FakeFile.path` being an instance of `pathlib.Path`?

```python
def test_one(fs: FakeFilesystem) -> None:
    fake_file = fs.create_file(FILE)
    isinstance(fake_file.path, pathlib.Path)  # False with pyfakefs==5.2.4
```

Thanks again as always btw!  We use `pyfakefs` to enable parallel test processes now.

**Comment by mrbean-bremen** [comment] 2023-08-25 17:24
> I am wondering, will create_file interact with the real filesystem if I use a pathlib.Path from the real file system?

Yes, I can confirm this (otherwise it would be a bug). What I was referring to was you creating the `foo` directory (`FOLDER.mkdir(exist_ok=True)`) in the test, as I wrote.

> What do you think of `FakeFile.path` being an instance of `pathlib.Path`?

I've thought about it. It depends a bit on how the return value is used. If it is used somewhere where a `pathlib.Path` is not allowed, this would break the code, e.g. it is a potentially breaking API change which I try to avoid in minor releases.
I could add another convenience function doing that, though that would be a bit of overkill. I haven't made my mind up yet...

**Comment by jamesbraza** [comment] 2023-08-25 17:58
Thanks per confirming everything! I guess having `FakeFile.path` as a primitive `str` is simple, and users can work with it from there.  Feel free to close this out as resolved 👍

**Comment by mrbean-bremen** [comment] 2023-08-26 16:36
Closing as answered, documentation has been updated.

**Closed by mrbean-bremen** 2023-08-26 16:36 UTC
Labels: question
