### ISSUE TITLE
Usable in Docker?

### ISSUE THREAD

**Issue by buhtz** [pytest-dev/pyfakefs#885] opened 2023-09-10 11:48 UTC
Sorry, this Issue is quit broad but I don't have a hot trail yet. Hope you can give me a hint.

Do you have experience with using pyfakefs related unittets in a Docker container?
Without Docker my tests do run green but inside Docker I got output like this.

```
mypytest_1  | FAILEDTraceback (most recent call last):
mypytest_1  |   File "/usr/local/lib/python3.8/site-packages/pyfakefs/fake_filesystem.py", line 1632, in get_object_from_normpath
mypytest_1  |     target = target.get_entry(component)  # type: ignore
mypytest_1  |   File "/usr/local/lib/python3.8/site-packages/pyfakefs/fake_file.py", line 542, in get_entry
mypytest_1  |     return self.entries[to_string(pathname_name)]
mypytest_1  | KeyError: 'work'
mypytest_1  | 
mypytest_1  | During handling of the above exception, another exception occurred:
mypytest_1  | 
mypytest_1  | Traceback (most recent call last):
mypytest_1  |   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
mypytest_1  |     return _run_code(code, main_globals, None,
mypytest_1  |   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
mypytest_1  |     exec(code, run_globals)
mypytest_1  |   File "/usr/local/lib/python3.8/site-packages/pytest/__main__.py", line 5, in <module>
mypytest_1  |     raise SystemExit(pytest.console_main())
mypytest_1  |   File "/usr/local/lib/python3.8/site-packages/_pytest/config/__init__.py", line 192, in console_main
mypytest_1  |     code = main()
mypytest_1  |   File "/usr/local/lib/python3.8/site-packages/_pytest/config/__init__.py", line 169, in main
mypytest_1  |     ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
mypytest_1  |   File "/usr/local/lib/python3.8/site-packages/pluggy/_hooks.py", line 493, in __call__
mypytest_1  |     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
mypytest_1  |   File "/usr/local/lib/python3.8/site-packages/pluggy/_manager.py", line 115, in _hookexec
mypytest_1  |     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
mypytest_1  |   File "/usr/local/lib/python3.8/site-packages/pluggy/_callers.py", line 113, in _multicall
mypytest_1  |     raise exception.with_traceback(exception.__traceback__)
mypytest_1  |   File "/usr/local/lib/python3.8/site-packages/pluggy/_callers.py", line 77, in _multicall
mypytest_1  |     res = hook_impl.function(*args)
mypytest_1  |   File "/usr/local/lib/python3.8/site-packages/_pytest/main.py", line 318, in pytest_cmdline_main
mypytest_1  |     return wrap_session(config, _main)
mypytest_1  |   File "/usr/local/lib/python3.8/site-packages/_pytest/main.py", line 303, in wrap_session
mypytest_1  |     os.chdir(session.startpath)
mypytest_1  |   File "/usr/local/lib/python3.8/site-packages/pyfakefs/fake_os.py", line 421, in chdir
mypytest_1  |     self.filesystem.confirmdir(path)
mypytest_1  |   File "/usr/local/lib/python3.8/site-packages/pyfakefs/fake_filesystem.py", line 2824, in confirmdir
mypytest_1  |     self.resolve(target_directory, check_owner=check_owner),
mypytest_1  |   File "/usr/local/lib/python3.8/site-packages/pyfakefs/fake_filesystem.py", line 1706, in resolve
mypytest_1  |     return self.get_object_from_normpath(
mypytest_1  |   File "/usr/local/lib/python3.8/site-packages/pyfakefs/fake_filesystem.py", line 1641, in get_object_from_normpath
mypytest_1  |     self.raise_os_error(errno.ENOENT, path)
mypytest_1  |   File "/usr/local/lib/python3.8/site-packages/pyfakefs/fake_filesystem.py", line 428, in raise_os_error
mypytest_1  |     raise OSError(err_no, message, filename)
mypytest_1  | FileNotFoundError: [Errno 2] No such file or directory in the fake filesystem: '/work/buhtzology'
python38_mypytest_1 exited with code 1

```

I'm unable to find the related location in my code. I just can say that "/work/buhtzology" is the current working directory in the container. But I don't understand why it can not be found because it exists in the cointainer. "/work/buhtzology".

**Comment by mrbean-bremen** [comment] 2023-09-10 14:37
The pyfakefs tests are run in docker containers [in the CI](https://github.com/pytest-dev/pyfakefs/actions/workflows/dockertests.yml) to test a few standard distributions, so yes - pyfakefs should work in a docker container.
The only issues that popped up so far have been problems because the tests are run as root by default, and this changes the behavior regarding permissions, and some issues with unicode if no locale was set in the container.

The error looks like the test is looking for the `work` directory in the fake filesystem (where it will not exist by default), so the question is _why_ it is looking there. Do you have an example test where that happens, or does happen with all tests? How you run the tests?

**Comment by buhtz** [comment] 2023-09-10 14:55
I will try to construct a full example. But I assume it is not related to the container.
I observed similar behavior in VirtualBox VM with Ubunt Focal (20.*).

```
FAILEDTraceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/pyfakefs/fake_filesystem.py", line 1632, in get_object_from_normpath
  File "/home/user/.local/lib/python3.8/site-packages/pyfakefs/fake_file.py", line 542, in get_entry
KeyError: 'home'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
  File "/home/user/.local/lib/python3.8/site-packages/pytest/__main__.py", line 5, in <module>
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/config/__init__.py", line 192, in console_main
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/config/__init__.py", line 169, in main
  File "/home/user/.local/lib/python3.8/site-packages/pluggy/_hooks.py", line 493, in __call__
  File "/home/user/.local/lib/python3.8/site-packages/pluggy/_manager.py", line 115, in _hookexec
  File "/home/user/.local/lib/python3.8/site-packages/pluggy/_callers.py", line 113, in _multicall
  File "/home/user/.local/lib/python3.8/site-packages/pluggy/_callers.py", line 77, in _multicall
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/main.py", line 318, in pytest_cmdline_main
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/main.py", line 303, in wrap_session
  File "/home/user/.local/lib/python3.8/site-packages/pyfakefs/fake_os.py", line 421, in chdir
  File "/home/user/.local/lib/python3.8/site-packages/pyfakefs/fake_filesystem.py", line 2824, in confirmdir
  File "/home/user/.local/lib/python3.8/site-packages/pyfakefs/fake_filesystem.py", line 1706, in resolve
  File "/home/user/.local/lib/python3.8/site-packages/pyfakefs/fake_filesystem.py", line 1641, in get_object_from_normpath
  File "/home/user/.local/lib/python3.8/site-packages/pyfakefs/fake_filesystem.py", line 428, in raise_os_error
FileNotFoundError: [Errno 2] No such file or directory in the fake filesystem: '/home/user/buhtzology'

```

The only similarity between the container and the VM is that both run with Python 3.8. I will investigate further and report back to you.

**Comment by buhtz** [comment] 2023-09-10 15:04
I can confirm that the error do not occur in the container when I use python3.9.

Python3.8 is nearly dead. Shouldn't invest much time in it.

**Comment by mrbean-bremen** [comment] 2023-09-10 15:37
I doubt that this is a 3.8 issue - would like very much understand it...

**Comment by mrbean-bremen** [comment] 2023-09-11 05:35
Did you use the same pytest version in both cases? It looks as if the problem arises because pytest partially uses the fake filesystem. 
Can you try to add `_pytest.main` to the skipped modules?

**Comment by buhtz** [comment] 2023-09-13 09:58
OK, I created an MWE to reproduce it. I'm not sure what it is but I wouldn't thay that Docker or a specific Python version is involved. I assume I make something wrong.

I haven't used Docker here. I can reproduce the problem using "unittest" and "pytest" with
 - Python 3.8.11 on Ubuntu 20 
 - Python 3.11 on Windows 10

The the full code and four log files attached in the ZIP.
[pyfs.zip](https://github.com/pytest-dev/pyfakefs/files/12596078/pyfs.zip)

The essential part of the error output
```
======================================================================
ERROR: setUpClass (test_pyfs.MyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buhtzch/work/pyfs/test_pyfs.py", line 26, in setUpClass
    with zipfile.ZipFile(cls.zip_filepath, 'w') as zip_handle:
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
  File "/home/buhtzch/.local/lib/python3.8/site-packages/pyfakefs/fake_io.py", line 117, in open
    return fake_open(
  File "/home/buhtzch/.local/lib/python3.8/site-packages/pyfakefs/fake_open.py", line 97, in __call__
    return self.call(*args, **kwargs)
  File "/home/buhtzch/.local/lib/python3.8/site-packages/pyfakefs/fake_open.py", line 199, in call
    file_object = self._init_file_object(
  File "/home/buhtzch/.local/lib/python3.8/site-packages/pyfakefs/fake_open.py", line 300, in _init_file_object
    file_object = self.filesystem.create_file_internally(
  File "/home/buhtzch/.local/lib/python3.8/site-packages/pyfakefs/fake_filesystem.py", line 2373, in create_file_internally
    self.raise_os_error(errno.ENOENT, parent_directory)
  File "/home/buhtzch/.local/lib/python3.8/site-packages/pyfakefs/fake_filesystem.py", line 428, in raise_os_error
    raise OSError(err_no, message, filename)
FileNotFoundError: [Errno 2] No such file or directory in the fake filesystem: '/home/buhtzch/work/pyfs'
```

Something went wrong in the `setUpClass()` and maybe the `zipfile` module is involved?

Here is the full code of the test file
```
import unittest
import platform
import pathlib
import zipfile
import pytest
import pyfakefs
import pyfakefs.fake_filesystem_unittest as pyfakefs_ut


class MyTest(pyfakefs_ut.TestCase):

    zip_filepath = pathlib.Path.cwd() / 'foo.zip'

    @classmethod
    def setUpClass(cls):

        print('')
        print(f'{platform.python_version()=}')
        print(f'{pyfakefs.__version__=}')
        print(f'{pytest.__version__=}')

        # Should generate zip file in a fake filesystem

        cls.setUpClassPyfakefs(allow_root_user=False)

        with zipfile.ZipFile(cls.zip_filepath, 'w') as zip_handle:
            with zip_handle.open('nice.txt', 'w') as entry_handle:
                entry_handle.write('foobar')

    def test_foobar(self):
        """Read and validate CSV from zip file."""

        self.assertTrue(zip_filepath.exists())

        # read
        with zipfile.ZipFile(cls.zip_filepath, 'r') as zip_handle:
            with zip_handle.open('nice.txt', 'r') as entry_handle:
                content = entry_handle.read()

        print(f'{content=}')

```

**Comment by mrbean-bremen** [comment] 2023-09-13 12:10
As far as I understand your code, you take an existing path in the real fs (`pathlib.Path.cwd()`), and then try to write a file into that (non-existing) path in the fake fs. You probably should create that path first...

**Comment by buhtz** [comment] 2023-09-13 14:26
Thanks for your reply. I'm not convinced yet but I'm also confused not sure which factor does influence the situation. Based on your comment I modified the code. I added more debug output and moved the "zip_filepath" from the class level into the functions **after** `setUpClassPyfakefs()` is called.

On Windows 10 with Py3.11 I'm not able to reproduce the problem anymore. But on Ubuntu 20 with Python 3.8 it is reproducible.

```
import unittest
import platform
import pathlib
import zipfile
import io
import pytest
import pyfakefs
import pyfakefs.fake_filesystem_unittest as pyfakefs_ut


class MyTest(pyfakefs_ut.TestCase):

    @classmethod
    def setUpClass(cls):

        print('')
        print(f'{platform.python_version()=}')
        print(f'{pyfakefs.__version__=}')
        print(f'{pytest.__version__=}')

        cls.setUpClassPyfakefs(allow_root_user=False)

        zip_filepath = pathlib.Path.cwd() / 'foo.zip'

        with zipfile.ZipFile(zip_filepath, 'w') as zip_handle:
            with zip_handle.open('nice.txt', 'w') as entry_handle:
                entry_handle.write(b'foobar')

        print(zip_filepath)
        print(zip_filepath.exists())
        print('\n===== end setUpClass() ===')

    def test_foobar(self):
        zip_filepath = pathlib.Path.cwd() / 'foo.zip'
        print(zip_filepath)
        print(zip_filepath.exists())

        self.assertTrue(zip_filepath.exists())

        # read
        with zip_filepath.open('rb') as handle:
            print('T'*55)
            stream = io.BytesIO(handle.read())
        print('U'*55)

        with zipfile.ZipFile(stream, 'r') as zip_handle:
            with zip_handle.open('nice.txt', 'r') as entry_handle:
                content = entry_handle.read()

        print(f'{content=}')

```

Looking into the debug output I can see that `zip_filepath` is not involved with the home path from the real filesystem. In both functions and as expected it is `C:\foo.zip` (on Windows) and `/foo.zip` (on Linux). Nothing wrong so far. Also `.exists()` returns `True`.

But (on the Linux machine) when I try to read from that file (`stream = io.BytesIO(handle.read())`) the error occurs.

    No such file or directory in the fake filesystem: '/home/buhtzch/work/pyfs'

This path in the error rmessage is the working directory. I wonder how this path comes into the fake filesystem? I mean how does pyfakefs or the fake filesystem know about it? Why does pyfakefs expect this path to exist in the fake filesystem? I never created that path and I never wrote a file into that path.

**Comment by mrbean-bremen** [comment] 2023-09-13 14:47
> I wonder how this path comes into the fake filesystem? I mean how does pyfakefs or the fake filesystem know about it? Why does pyfakefs expect this path to exist in the fake filesystem? I never created that path and I never wrote a file into that path.

True - out of my head I have no idea. I will have a closer look later - thanks for all your investigative work!

**Comment by mrbean-bremen** [comment] 2023-09-13 19:23
Hm, I've just taken your example test and [ran it in the CI](https://github.com/mrbean-bremen/pyfakefs/actions/runs/6176859376), and it works fine for all OSes and Python versions (including Python 3.8 under Ubuntu 20.04 - you can ignore that PyPy3.7 error, it is unrelated).
Can you please check what `str(zip_filepath)` is after you define it (before the crash, obviously), and for good measure also `os.getcwd()`? I have no idea how to reproduce this...
Are you running the test alone, or are there other tests run before that could influence the environment? I've used pytest for testing, as you wrote it happens regardless of the test runner, is this still the case?

**Comment by buhtz** [comment] 2023-09-18 13:27
I'm far away from being sure but I do have a feeling that it could be related to the introduction of `setUpClassPyfakefs()`.

Here is the current state of the code with your requested modifications:

```
import unittest                                                                                                                                                                               import platform                                                                                                                                                                               import pathlib                                                                                                                                                                                import zipfile                                                                                                                                                                                import io                                                                                                                                                                                     import os                                                                                                                                                                                     import pytest                                                                                                                                                                                 import pyfakefs                                                                                                                                                                               import pyfakefs.fake_filesystem_unittest as pyfakefs_ut                                                                                                                                                                                                                                                                                                                                     
class MyTest(pyfakefs_ut.TestCase):

    @classmethod
    def setUpClass(cls):

        print('')
        print(f'{platform.python_version()=}')
        print(f'{pyfakefs.__version__=}')
        print(f'{pytest.__version__=}')

        print(f'before setUpClassPyfakefs() :: {os.getcwd()=}')
        cls.setUpClassPyfakefs(allow_root_user=False)

        zip_filepath = pathlib.Path.cwd() / 'foo.zip'
        print(f'{str(zip_filepath)=}')
        print(f'after setUpClassPyfakefs() :: {os.getcwd()=}')

        with zipfile.ZipFile(zip_filepath, 'w') as zip_handle:
            with zip_handle.open('nice.txt', 'w') as entry_handle:
                entry_handle.write(b'foobar')

        print(zip_filepath)
        print(zip_filepath.exists())
        print('\n===== end setUpClass() ===')

    def test_foobar(self):
        zip_filepath = pathlib.Path.cwd() / 'foo.zip'
        print(zip_filepath)
        print(zip_filepath.exists())

        self.assertTrue(zip_filepath.exists())

        # read
        # with zip_filepath.open('rb') as handle:
        print('X'*55)
        with open(str(zip_filepath), 'rb') as handle:
            print('T'*55)
            stream = io.BytesIO(handle.read())
        print('U'*55)

        with zipfile.ZipFile(stream, 'r') as zip_handle:
            with zip_handle.open('nice.txt', 'r') as entry_handle:
                content = entry_handle.read()

        print(f'{content=}')


```

Here is the output.

```
$ python3 -m pytest test_pyfs.py -vsx                                                                                                                    [10/100]==================================================================================== test session starts =====================================================================================platform linux -- Python 3.8.10, pytest-4.6.9, py-1.8.1, pluggy-1.3.0 -- /usr/bin/python3                                                                                                     cachedir: .pytest_cache                                                                                                                                                                       rootdir: /home/buhtzch/work/pyfs                                                                                                                                                              plugins: pyfakefs-5.2.4                                                                                                                                                                       collected 1 item                                                                                                                                                                                                                                                                                                                                                                            test_pyfs.py::MyTest::test_foobar                                                                                                                                                             platform.python_version()='3.8.10'                                                                                                                                                            pyfakefs.__version__='5.2.4'                                                                                                                                                                  pytest.__version__='4.6.9'
before setUpClassPyfakefs() :: os.getcwd()='/home/buhtzch/work/pyfs'
Clearing the cache
str(zip_filepath)='/foo.zip'
after setUpClassPyfakefs() :: os.getcwd()='/'
/foo.zip
True

===== end setUpClass() ===
/foo.zip
True
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU
content=b'foobar'
PASSEDTraceback (most recent call last):
  File "/home/buhtzch/.local/lib/python3.8/site-packages/pyfakefs/fake_filesystem.py", line 1632, in get_object_from_normpath
  File "/home/buhtzch/.local/lib/python3.8/site-packages/pyfakefs/fake_file.py", line 542, in get_entry
KeyError: 'home'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/py/_error.py", line 66, in checked_call
  File "/home/buhtzch/.local/lib/python3.8/site-packages/pyfakefs/fake_os.py", line 421, in chdir
  File "/home/buhtzch/.local/lib/python3.8/site-packages/pyfakefs/fake_filesystem.py", line 2824, in confirmdir
  File "/home/buhtzch/.local/lib/python3.8/site-packages/pyfakefs/fake_filesystem.py", line 1706, in resolve
  File "/home/buhtzch/.local/lib/python3.8/site-packages/pyfakefs/fake_filesystem.py", line 1641, in get_object_from_normpath
  File "/home/buhtzch/.local/lib/python3.8/site-packages/pyfakefs/fake_filesystem.py", line 428, in raise_os_error
FileNotFoundError: [Errno 2] No such file or directory in the fake filesystem: '/home/buhtzch/work/pyfs'

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
  File "/usr/lib/python3/dist-packages/pytest.py", line 102, in <module>
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 82, in main
  File "/home/buhtzch/.local/lib/python3.8/site-packages/pluggy/_hooks.py", line 493, in __call__
  File "/home/buhtzch/.local/lib/python3.8/site-packages/pluggy/_manager.py", line 115, in _hookexec
  File "/home/buhtzch/.local/lib/python3.8/site-packages/pluggy/_callers.py", line 113, in _multicall
  File "/home/buhtzch/.local/lib/python3.8/site-packages/pluggy/_callers.py", line 77, in _multicall
  File "/usr/lib/python3/dist-packages/_pytest/main.py", line 243, in pytest_cmdline_main
  File "/usr/lib/python3/dist-packages/_pytest/main.py", line 233, in wrap_session
  File "/usr/lib/python3/dist-packages/py/_path/local.py", line 576, in chdir
  File "/usr/lib/python3/dist-packages/py/_error.py", line 86, in checked_call
py.error.ENOENT: [No such file or directory]: chdir('/home/buhtzch/work/pyfs',)
```

**Comment by mrbean-bremen** [comment] 2023-09-18 18:31
Ok, I could not reproduce this at first either, but then I did a test [with several pytest versions](https://github.com/mrbean-bremen/pyfakefs/actions/runs/6226467910), and could reproduce it with pytest versions < 6.2 under all systems and Python versions. I had tested with the latest pytest version before, thus I couldn't reproduce it.

At least there seems to be a workaround for now - just use a current pytest version. As it is not guaranteed that this will not break again with a later version, I will see if I can find the root cause, and hopefully do something about it.

**Comment by mrbean-bremen** [comment] 2023-09-18 18:56
Found the issue. This was a [pytest issue](https://github.com/pytest-dev/pytest/issues/8032) - `addClassCleanup` was not properly called, which let to pyfakefs code bleeding into pytest code (e.g. the filesystem was still faked during pytest shutdown).  So you have been right - it had to do with `setUpClassPyfakefs` (which I also suspected given that the feature is relatively new).  
`addClassCleanup` has only been added in Python 3.8, which is also the reason that `setUpClassPyfakefs` only works starting with that version.

So yes, the class setup in combination with pytest was the problem. Note that using the respective class, module and session scoped pytest fixtures shall work as expected, the problem only occurs if mixing unittest and pytest in this case.

I will later add a note that `setUpClassPyfakefs` is only usable in combination with a pytest runner starting with pytest 6.2.0. Thanks for helping to pin this down!

**Comment by buhtz** [comment] 2023-09-18 18:58
Great! Why it is always me finding this curios problems? :laughing: 
It is a pleasure to work with you.

**Comment by buhtz** [comment] 2023-09-18 19:20
> I will later add a note that `setUpClassPyfakefs` is only usable in combination with a pytest runner starting with pytest 6.2.0. Thanks for helping to pin this down!

Mhm... Are you so sure about the pytest version? See my pyfs.zip file and the logs in there.
I reproduce the problem with "unittest" and with "pyfakefs 7.4.2" also.

**Comment by mrbean-bremen** [comment] 2023-09-18 19:29
Well... did you check my [linked test results](https://github.com/mrbean-bremen/pyfakefs/actions/runs/6226408791)? 
I had no luck at all with newer pytest versions, and given that the pytest issue is exactly what would lead to the problem, I'm pretty sure... Though you may convince me otherwise.

**Comment by mrbean-bremen** [comment] 2023-09-18 19:31
Oh, and in your log file I see "pytest-4.6.9" for Python 3.8 - this is quite old.

**Comment by buhtz** [comment] 2023-09-18 19:43
Maybe it is because I always do `import pytest` (because I print its version) but run the tests with `python3 -m unittest`?

**Comment by mrbean-bremen** [comment] 2023-09-18 20:26
Hm, that is weird. If you run the tests with unittest, why you are getting a call stack in pytest code? Something does not match here...

**Comment by buhtz** [comment] 2023-09-26 18:03
Reproducibility is still a problem.
Currently I refused to use `setUpClassPyfakefs()` and "migrated back" to `setUpPyfakefs()`. This works fine for me.

This issue might come up later again. I will have an eye on it and report back.

Feel free to close the issue.

**Comment by mrbean-bremen** [comment] 2023-09-27 06:32
Thanks for trying. I'll leave that open for a bit - maybe I can have another look myself when I get back to a computer (I'm away for a couple of weeks), and if I can't find anything, I will close this for the time being.

**Comment by mrbean-bremen** [comment] 2023-10-08 12:03
Closing this for now - please reopen if you find out how to reproduce the problem.

**Closed by mrbean-bremen** 2023-10-08 12:03 UTC
Labels: info needed
